name: jalawave
services:
  jalawave-database-mongo:
    image: mongo 
    container_name: jalawave-database-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jalawave
      - MONGO_INITDB_ROOT_PASSWORD=j4l4w4v3123
      - MONGO_INITDB_DATABASE=genieacs
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log/mongodb
    ports:
      - "27017:27017"
    volumes:
      - jalawave-database-mongo:/data/db
      - jalawave-database-mongo-config:/data/configdb
    networks:
      - jalawave
    restart: always
    privileged: false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  jalawave-genieacs:
    depends_on:
      - 'jalawave-database-mongo'
    image: dedisalam/jalawave-genieacs
    container_name: jalawave-genieacs
    environment:
      - GENIEACS_UI_JWT_SECRET=jalawavecakrawala
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://jalawave:j4l4w4v3123@jalawave-database-mongo:27017/genieacs?authSource=admin
      - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cmwp-access.log
      - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
      - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
      - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
      - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
      - GENIEACS_EXT_DIR=/opt/genieacs/ext
      - GENIEACS_UI_PORT=3001
    ports:
      - "7547:7547"
      - "7557:7557"
      - "7567:7567"
      - "3001:3001"
    volumes:
      - jalawave-genieacs:/opt
      - ./ext:/opt/genieacs/ext/
    networks:
      - jalawave
    restart: always
    privileged: false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  jalawave-database-mongo:
    name: jalawave-database-mongo
  jalawave-database-mongo-config:
    name: jalawave-database-mongo-config
  jalawave-genieacs:
    name: jalawave-genieacs

networks:
  jalawave:
    name: jalawave